-- sql to create a scehema names tps
CREATE SCHEMA tps;

-- sql to create a table in the schema tps
CREATE TABLE tps.major_crime_t (
    OBJECTID SERIAL PRIMARY KEY,
    EVENT_UNIQUE_ID VARCHAR(50) NOT NULL,
    REPORT_DATE TIMESTAMP NOT NULL,
    OCC_DATE TIMESTAMP NOT NULL,
    REPORT_YEAR INT NOT NULL,
    REPORT_MONTH VARCHAR(20) NOT NULL,
    REPORT_DAY INT NOT NULL,
    REPORT_DOY INT NOT NULL,
    REPORT_DOW VARCHAR(20) NOT NULL,
    REPORT_HOUR INT NOT NULL,
    OCC_YEAR INT NOT NULL,
    OCC_MONTH VARCHAR(20) NOT NULL,
    OCC_DAY INT NOT NULL,
    OCC_DOY INT NOT NULL,
    OCC_DOW VARCHAR(20) NOT NULL,
    OCC_HOUR INT NOT NULL,
    DIVISION VARCHAR(10) NOT NULL,
    LOCATION_TYPE TEXT NOT NULL,
    PREMISES_TYPE VARCHAR(50) NOT NULL,
    UCR_CODE VARCHAR(10) NOT NULL,
    UCR_EXT INT NOT NULL,
    OFFENCE VARCHAR(50) NOT NULL,
    MCI_CATEGORY VARCHAR(50) NOT NULL,
    HOOD_158 VARCHAR(50) NOT NULL,
    NEIGHBOURHOOD_158 VARCHAR(50) NOT NULL,
    HOOD_140 VARCHAR(50) NOT NULL,
    NEIGHBOURHOOD_140 VARCHAR(50) NOT NULL,
    LONG_WGS84 DOUBLE PRECISION NOT NULL,
    LAT_WGS84 DOUBLE PRECISION NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL
);