-- sql to create a scehema names tps
CREATE SCHEMA tps;

-- sql to create a table in the schema tps
CREATE TABLE tps.major_crime_t (
    OBJECTID SERIAL PRIMARY KEY,
    EVENT_UNIQUE_ID VARCHAR(50),
    REPORT_DATE TIMESTAMP,
    OCC_DATE TIMESTAMP,
    REPORT_YEAR INT,
    REPORT_MONTH VARCHAR(20),
    REPORT_DAY INT,
    REPORT_DOY INT,
    REPORT_DOW VARCHAR(20),
    REPORT_HOUR INT,
    OCC_YEAR INT,
    OCC_MONTH VARCHAR(20),
    OCC_DAY INT,
    OCC_DOY INT,
    OCC_DOW VARCHAR(20),
    OCC_HOUR INT,
    DIVISION VARCHAR(10),
    LOCATION_TYPE TEXT,
    PREMISES_TYPE VARCHAR(50),
    UCR_CODE VARCHAR(10),
    UCR_EXT INT,
    OFFENCE VARCHAR(50),
    MCI_CATEGORY VARCHAR(50),
    HOOD_158 VARCHAR(50),
    NEIGHBOURHOOD_158 VARCHAR(50),
    HOOD_140 VARCHAR(50),
    NEIGHBOURHOOD_140 VARCHAR(50),
    LONG_WGS84 DOUBLE PRECISION,
    LAT_WGS84 DOUBLE PRECISION,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION
);

-- sql to create a homocide_t table in the schema tps
CREATE TABLE tps.homicide_t (
    OBJECTID SERIAL PRIMARY KEY,
    EVENT_UNIQUE_ID VARCHAR(50),
    OCC_DATE TIMESTAMP,
    OCC_YEAR INT,
    OCC_MONTH VARCHAR(20),
    OCC_DAY INT,
    OCC_DOW VARCHAR(20),
    OCC_DOY INT,
    DIVISION VARCHAR(10),
    HOMICIDE_TYPE VARCHAR(50),
    HOOD_158 VARCHAR(50),
    NEIGHBOURHOOD_158 VARCHAR(50),
    HOOD_140 VARCHAR(50),
    NEIGHBOURHOOD_140 VARCHAR(50),
    LONG_WGS84 DOUBLE PRECISION,
    LAT_WGS84 DOUBLE PRECISION,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION
);

